services:
  shalini-app:
    image: varshney30/shalini-script:latest
    container_name: shalini-day8
    restart: always

  nginx:
    image: nginx:alpine
    container_name: shalini-nginx
    ports:
      - "8080:80"
    volumes:
      -./html:/usr/nginx/html
    restart: always
